name: Backrooms
version: '${project.version}'
main: lampteam.backrooms.Backrooms
api-version: 1.16
authors: [ steyn91 ]
commands:
  br:
    description: backrooms goes brrrrr
  party:
    description: invite friends
  bradmin:
    description: if something doesn't work